types = {
    ["A-10A"] = {livery = "fictional spanish 12nd wing"},
    ["A-10C"] = {livery = "fictional spanish 12nd wing"},
    ["A-10C_2"] = {livery = "354th fs davis monthan afb, arizona (dm)"},
    ["Bf-109K-4"] = {livery = "Bf-109 K4 Dogfight RED"},
    ["F-15C"] = {livery = "493rd Fighter SQN (LN)"},
    ["F-16C_50"] = {livery = "132nd_wing _iowa_ang"},
    ["F-5E-3"] = {livery = "aggressor desert scheme"},
    ["F-5E-3_FC"] = {livery = "ch j-3001 variante 2000"},
    ["F-86F Sabre"] = {livery = "us air force (skyblazers)"},
    ["F-86F_FC"] = {livery = "us air force (skyblazers)"},
    ["FA-18C_hornet"] = {livery = "spain 151th escuadron c.15-18"},
    ["FW-190A8"] = {livery = "Black 13 Schwarze Katze from JG1"},
    ["FW-190D9"] = {livery = "FW-190D9_5JG301"},
    ["J-11A"] = {livery = "sky hunter"},
    ["L-39C"] = {livery = "slovak air force"},
    ["L-39ZA"] = {livery = "algerian af nl-44"},
    ["MiG-15bis"] = {livery = "polish_air force"},
    ["MiG-15bis_FC"] = {livery = "polish_air force"},
    ["MiG-29 Fulcrum"] = {livery = "rf domna afb"},
    ["MiG-29A"] = {livery = "Vasylkiv 40th BrTA"},
    ["MiG-29G"] = {livery = "luftwaffe gray-1"},
    ["MiG-29S"] = {livery = "KazAADF new faded (fictional)"},
    ["P-47D-30"] = {livery = "61st_fs_1944"},
    ["P-47D-30bl1"] = {livery = "61st_fs_1944"},
    ["P-47D-40"] = {livery = "61st_fs_1944"},
    ["P-51D"] = {livery = "RAF 315 Sqdn Jun 44"},
    ["P-51D-30-NA"] = {livery = "RAF 315 Sqdn Jun 44"},
    ["SpitfireLFMkIX"] = {livery = "rnoaf blade norwegian ah-g"},
    ["SpitfireLFMkIXCW"] = {livery = "ussr_3rd_ae_57th_gviap"},
    ["Su-25"] = {livery = "IRGC 54"},
    ["Su-25T"] = {livery = "Algerian AF Trainer KU-04"},
    ["Su-27"] = {livery = "PLAAF Standard"},
    ["Su-33"] = {livery = "279th kiap 1st squad Syria 2017"},
    ["TF-51D"] = {livery = "tf-51 glamorous glen iii"},
    ["Yak-52"] = {livery = "bare_metall"},
}
